require("core.options")
require("core.keymaps")
require("plugins.setup")

-- 插件
require("plugins/autopairs")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/bufferline")
require("plugins/telescope")
require("plugins/toggleterm")
require("plugins/lualine")
require("plugins/lsp")
require("plugins/vim-go")
require("plugins/cmp")
require("plugins/asyncrun")
--require("plugins/undotree")
require("plugins/vim-arsync")
require("plugins/mason")
require("plugins/nvim-lastplace")
