-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.options")
require("config.autocmds")
require("config.keymaps")
require("config.lazy")

------ 插件
----require("plugins/nvim-tree")
----require("plugins/treesitter")
----require("plugins/bufferline")
----require("plugins/flash")
----require("plugins/telescope")
----require("plugins/toggleterm")
----require("plugins/lualine")
----require("plugins/autopairs")
----require("plugins/aerial")
----require("plugins/vim-go")
----require("plugins/lsp")
----require("plugins/cmp")
----require("plugins/mason")
----require("plugins/asyncrun")
------require("plugins/undotree")
------require("plugins/vim-arsync")
----require("plugins/nvim-lastplace")
------require("plugins/comment")
----require("plugins/trans")
