-- set the undotree window layout
-- vim.g.undotree_WindowLayout = 2
-- the undotree window will get focus after being opened
-- vim.g.undotree_SetFocusWhenToggle = 1
--
-- local keymap = vim.keymap
--
-- keymap.set("n", "<F5>", ":UndotreeToggle<CR>", {noremap = true, silent = true})
